### ISSUE TITLE
[BUG] - Niet-conforme tooltip word getoond

### ISSUE THREAD

**Issue by cambiph** [milieuinfo/webcomponent-vl-ui-form-validation#18]
**Omschrijf het probleem**
Wanneer je een foutief e-mailadres ingeeft en vervolgens op valideren klikt, krijg je een niet conforme tooltip te zien:

**Hoe te reproduceren**
Vul een foutief e-mailadres in en klik op valideren.

**Gewenst gedrag**

**Screenshots**

![image-2020-02-17-10-25-41-723](https://user-images.githubusercontent.com/1628243/75759119-5a6d8c00-5d35-11ea-9110-e3ae9c3d8b62.png)

**Comment by driesva** [comment]
Dit komt omdat input `type="email"` wordt gebruikt en HTML5 validatie blijkbaar niet goed werkt in combinatie met form-validation...
