### ISSUE TITLE
[FEATURE] - Rijksregisternummer modulo validatie

### ISSUE THREAD

**Issue by coemans** [milieuinfo/webcomponent-vl-ui-form-validation#19]
**Wat moet er gebeuren**
Rijksregisternummer module validatie toevoegen.

**Extra info**
Dit is besproken met Webuniversum, dus PR bij hen aan te maken zodat dit centraal verwerkt kan worden.

**Comment by philipperutten** [comment]
Rekening te houden met het volgende: RR nrs bevatten een modulo-97 controlegetal. Hiermee is de geldigheid van een nummer te controleren zonder daarvoor het RR te moeten raadplegen. Probleem: het RR berekent het controlegetal niet op een eenduidige manier. Voor iedereen geboren VOOR 2000, wordt het controlegetal 'normaal' berekend obv de eerste 9 cijfers van het nummer. Voor iedereen geboren IN of NA 2000, daarentegen, wordt er, voor de modulo-97 berekening, eerst een 2 vóór die 9 cijfers gezet. Bijgevolg komt het resulterende controlegetal dus niet meer overeen met de 9 eerste cijfers van het betreffende RR nr. Wat betekent, dat als je op zo'n RR nr een 'normale' modulo-97 check zou doen, deze faalt. Terwijl het dus eigenlijk wel degelijk een geldig nummer is. We zullen dus een dubbele check moeten inbouwen, namelijk: faalt de gewone check, dan moeten we checken met een 2 ervoor.

**Comment by driesva** [comment]
Er moet ook (optionele?) ondersteuning zijn voor BIS-nummers en gevallen waar exacte geboortedatum niet gekend is. Dus eigenlijk hebben we een algemene INSZ validatie nodig.

Zie: 
- https://overheid.vlaanderen.be/insz-nummer
- https://www.ksz-bcss.fgov.be/nl/diensten-en-support/diensten/rijksregisterksz-registers
- https://www.ksz-bcss.fgov.be/sites/default/files/assets/diensten_en_support/tss_registries_concepts_nl.docx

Ter info, hier is een lijst van BIS-nummers die we verkregen hebben van VKBP T&I:

- 00200105357
- 31200141753
- 54400115070
- 62460102022
- 76490104224
- 88490101611
- 99290102296
- 14292600433
- 24290509079
- 44510301908

Enkele geldige speciale gevallen waar bij exacte datum niet gekend is:
- 33000008427
- 00000000128
- 44000028161

**Comment by coemans** [comment]
@driesva ik heb bovenstaande nummers ingevuld en met de huidige (nieuwe) validatie zijn ze allemaal validatie, er lijkt dus momenteel geen extra uitbreiding nodig te zijn aan de code.
