### ISSUE TITLE
[FEATURE] - Validatie internationaal e-mailadres

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-form-validation#21]
**Wat moet er gebeuren**
Bij een vorige review van onze code werd aangehaald dat we custom validatie gebruiken en niet de richtlijnen omtrent standaard form validatie volgen.
Echter lijkt het dat de form-validation nog steeds niet aan onze vereisten voldoet. Wij willen [internationale e-mailadressen](https://en.wikipedia.org/wiki/International_email) toestaan omdat er ook buitenlandse gebruikers zijn.

Bijvoorbeeld het volgende e-mailadres werkt niet: Dörte@Sörensen.example.com

Dus `data-vl-validation-type="email"` is niet bruikbaar. Bovendien is er geen alternatief om een patroon mee te geven.

**Extra info**

- In standaard HTML5 is het volgende mogelijk:
```
<form action="/">
  <label for="email">Email:</label>
  <input  id="email"  name="email" pattern="^[^@]+@[^@]+\.[^@]+$">
  <input type="submit">
</form>
```

- Het lijkt er ook op dat form validation zich ongewild registreert bij het definiëren van een input field binnen een form: 
```
    <form>
            <input is="vl-input-field" 
                   id="email"
                   maxlength="254"
                   placeholder="email@provider.com"
                   block
                 >
<!-- ... -->
```
En dit geeft volgende error:
```
TypeError: e is null form-validation.min.js:2616:6
    F form-validation.min.js:2616
    value form-validation.min.js:2680
    later core.js:62
    (Async: setTimeout handler)
    debounce core.js:68
    (Async: EventListener.handleEvent)
    value form-validation.min.js:2679
    each core.js:303
    value form-validation.min.js:2634
    dress vl-form-validation.min.js:11
    _dress vl-input-field.min.js:20
    connectedCallback vl-input-field.min.js:12
```
Je kan dan met `novalidate` werken, maar dat zet ook native validatie af.

**Comment by kevcraey** [comment]
https://www.milieuinfo.be/jira/browse/UIG-2197
