### ISSUE TITLE
[FEATURE] - Introductie isValid property

### ISSUE THREAD

**Issue by ZhaodiFengVlaanderen** [milieuinfo/webcomponent-vl-ui-form-validation#45]
**Wat moet er gebeuren**
Zou graag vl-ui-form-validation een isValid property aanbieden.
Momenteel moet ik in de class list checken, maar dit lijkt mij tricky.

**Comment by coemans** [comment]
@ZhaodiFengVlaanderen kan je hiervoor gebruik maken van de form `checkValidity` functie?

**Comment by ZhaodiFengVlaanderen** [comment]
> @ZhaodiFengVlaanderen kan je hiervoor gebruik maken van de form `checkValidity` functie?

zou proberen

**Comment by ZhaodiFengVlaanderen** [comment]
checkValidity werkt niet goed met input event, waarschijnlijke door dat de value van input nog niet effectieve aangepaste is...

**Comment by coemans** [comment]
De `checkValidity` functie dient om de validiteit te controleren, maar de validatie moet dan natuurlijk al gebeurd zijn. Als jullie geen submit knop hebben, kan de validatie op één veld geactiveerd worden door bijvoorbeeld het change event te propageren: `input.dispatchEvent(new Event('change'))`.

**Comment by ZhaodiFengVlaanderen** [comment]
Dus ik moet in mijn "input" event-listener een "change" event dispatch. 
En de checkValidity functie aanroepen in de "change" event-listener.
Lijk mij wel te werken.

**Comment by coemans** [comment]
Prima, dan kan dit issue afgesloten worden.

**Comment by ZhaodiFengVlaanderen** [comment]
@coemans, ik heb de "change" event geprobeerd, maar lijk mij niet te werken.
De validatie is niet getriggert en de gekopieerd waard wordt ook niet juiste gevalideerd.
Misschien heb ik toch een methode nodig om de validatie te kunnen starten.
Ik heb een issue gemaakt: https://github.com/milieuinfo/webcomponent-vl-ui-form-validation/issues/57
