### ISSUE TITLE
[BUG] - Disable Form redirect

### ISSUE THREAD

**Issue by ZhaodiFengVlaanderen** [milieuinfo/webcomponent-vl-ui-form-validation#48]
**Omschrijf het probleem**
In combinatie met Lit, kan de form redirection niet uitschakelen met standaard gedragen, zoals:

- event.preventDefault() in onSubmit event listener

- onSubmit return false

Momenteel gebruik ik hiervoor een trick, namelijke submit de form naar een iframe:
`<iframe id="preventRedirectRef"
              name="preventRedirectRef"
              src="about:blank"
              aria-hidden="true"
              hidden="true">
      </iframe>
      <form data-vl-validate-form-success="true" target="preventRedirectRef"
            method="post"
            action="about:blank">
      ...
     </form>`

**Comment by coemans** [comment]
@ZhaodiFengVlaanderen dat lijkt me momenteel de beste manier van werken, al heb ik een [vl-ui-form](https://github.com/milieuinfo/webcomponent-vl-ui-form/pull/2) component geïntroduceerd zodat niet iedereen dit zelf moet toepassen.
