### ISSUE TITLE
[BUG] - Volgorde van zoom/focus op formvelden 

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-form-validation#66]
**Omschrijf het probleem**
Wanneer er validatiefouten zijn op verschillende form-velden, wordt er niet naar de volgorde in de DOM gekeken. Maar naar het type van het form-veld. Volgorde is precies `<input/>`, `<datepicker/>`, `<select/>`, ...

**Hoe te reproduceren**
Form met verschillende type velden door elkaar zetten en herhalen eventueel. Form laten valideren toont aan dat het niet per se naar de eerste error scrollt/focust.

**Comment by coemans** [comment]
Dit is gerelateerd aan [#99](https://github.com/milieuinfo/webcomponent-vl-ui-checkbox/issues/99). Best even de Chromium update afwachten voordat we verder actie ondernemen.

**Comment by kevcraey** [comment]
https://www.milieuinfo.be/jira/browse/UIG-2196
