### ISSUE TITLE
[BUG] - form data ophalen op form niveau zelf

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-form-validation#67]
**Omschrijf het probleem**
Momenteel is het niet mogelijk om voor de volgende componenten de data via de form (met FormData) te verkrijgen:

- vl-datepicker
- vl-upload
- vl-textarea
- vl-select

Mogelijks zullen er nog zijn, maar dit zijn diegene die voorlopig nodig zijn voor IBO. Misschien dat de andere componenten meteen mee getest worden? 

**Hoe te reproduceren**
form opbouwen met bovenstaande componenten en dan proberen de data op te halen van de form.

``` JavaScript
//form ophalen
this._form = queryById(this)("inspraak-form") 
...
//formdata verkrijgen
let data = new FormData(this._form);
...
//data van een select veld halen --> dit lukt voorlopig nog niet en geeft null terug
form.get('dossierType')
```

**Gewenst gedrag**
Alle componenten binnen de form hun data op dezelfde manier raadpleegbaar maken op form niveau.

**Comment by Rubenth** [comment]
FYI: wanneer ik over all key - value pairs van de form loop, krijg ik effectief geen key waardes te zien voor alle andere form-velden binnen mijn form. Ik krijg namelijk maar 3/9 key-value formvelden te zien.
`          let data = new FormData(this._form);
          for(var pair of data.entries()){
            console.log(pair[0]+ ', ' + pair[1]);
          }`

**Comment by kevcraey** [comment]
https://www.milieuinfo.be/jira/browse/UIG-2195
