### ISSUE TITLE
[FEATURE] - custom validation voor elke component die propageert naar form validity 

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-form-validation#69]
**Wat moet er gebeuren**
Op elke form veld component zouden we een custom validatie aan willen meegeven. 

Bijvoorbeeld bij het gebruik van vl-form-validation in IBO is de standaard form-validation niet voldoende. Bij de vl-upload heb je namelijk al basic validatie op required, fileSize en fileExtension. Maar binnen IBO controleren we de inhoud van het opgeladen bestand. En op basis hiervan willen we dat de form zijn validity ook aanpast en bijgevolg ook de error attributen en messages correct toepast.

Zo moeten we bij het submitten van de form enkel controleren mbv form.checkValidity() of deze nog errors bevat of niet. 

**Extra info**
Voorbeeldcode van extra validatie binnen ibo. Hier aanvaarden we op de component enkel .zip files. En vervolgens kijken we naar de inhoud, als deze unzipped file niet de juiste bestanden bevat dan gaan we een error teruggeven. 
Er moet dus ook per validatiefout een errormessage meegegeven kunnen worden. 
```
export const readShapeFileToGeoJson = async (inputFiles) => {
  if (inputFiles.length !== 1) {
    return {errors: [NO_FILE]};
  }
  const inputFile = inputFiles[0];
  if (!inputFile.name.endsWith('.zip')) {
    return {errors: [NOT_ZIP]};
  }
  // .default nodig voor es-dev-server -> geen invloed op bundled package
  const zip = await JSZip.default().loadAsync(inputFile);

  const invalidExtensions = Object.keys(zip.files)
  .filter(fn => !ALLOWED_EXTENSIONS.some(ext => fn.toLowerCase().endsWith(ext)));
  if (invalidExtensions.length !== 0) {
    return {errors: [INVALID_EXTENSION]};
  }

  let zipFiles = zip.file(/.*\.shp$/);
  if (zipFiles.length === 0) {
    return {errors: [NO_SHP_FILES]};
  }
  if (zipFiles.length > 1) {
    return {errors: [MULTIPLE_SHP_FILES]};
  }
  const content = await zipFiles[0].async("arraybuffer");
  let featureCollection = await shapefile.read(content);
  return readAndMergeFeaturesFromCollection(featureCollection)
};
```

**Comment by kevcraey** [comment]
https://www.milieuinfo.be/jira/browse/UIG-2194
