### ISSUE TITLE
[BUG] - vl-select en vl-textarea geven error state niet door aan form.checkValidity() 

### ISSUE THREAD

**Issue by Rubenth** [milieuinfo/webcomponent-vl-ui-form-validation#70]
**Omschrijf het probleem**
` form.checkValidity()` geeft true terug wanneer er nog fouten zijn op vl-select of vl-textarea componenten. (Mogelijks zijn er nog form componenten met deze issue.)

**Hoe te reproduceren**
Form bouwen met daarin vl-textarea/vl-select velden en form.checkValidity() uitvoeren in console of code.
`code snippet`

**Gewenst gedrag**
false doorgeven aan form validity check

**Comment by coemans** [comment]
In het geval van vl-ui-select vermoedelijk gerelateerd aan issue [#157](https://github.com/milieuinfo/webcomponent-vl-ui-select/issues/157) en opgelost in PR [#159](https://github.com/milieuinfo/webcomponent-vl-ui-select/pull/159). Het zou kunnen dat de code wijzigingen ook het probleem oplossen voor vl-ui-textarea, nog te valideren.

**Comment by coemans** [comment]
Het probleem lijkt inderdaad ook opgelost na update vl-ui-form-validation op vl-ui-textarea via PR [#101](https://github.com/milieuinfo/webcomponent-vl-ui-textarea/pull/101). Er zal nog een upgrade gebeuren voor de andere form componenten.
